FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json .npmrc eslint.config.js ./
COPY config ./config

RUN npm install

RUN npm run lint

COPY src ./src

EXPOSE 3001

CMD ["npm", "run", "dev"]
